[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
# 🚀 Add this line to fix the Amoy warning
# 🚀 FORCE VERSION & COMPATIBILITY
solc_version = "0.8.20"
evm_version = "paris"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
